###################### Winlogbeat → Kafka ########################

winlogbeat.event_logs:
  # Application Log - Only security-related application errors
  - name: Application
    ignore_older: 1h
    start_position: latest
    level: error, critical
    providers:
      - "Microsoft-Windows-Security"
      - "MSSQLSERVER"
      - "SQLServer"
    fields:
      log_type: "application"

  # System Log - Only critical system errors
  - name: System
    ignore_older: 1h
    start_position: latest
    level: error, critical
    fields:
      log_type: "system"

# ====================== QUEUE SETTINGS =======================
queue:
  mem:
    events: 512  # Reduced from 2048
    flush:
      min_events: 50   # Further reduced
      timeout: 2s      # Increased slightly

# ====================== PROCESSORS =======================
processors:
  - add_fields:
      target: ''
      fields:
        siem_priority: "high"
        environment: "production"
  
  - drop_event:
      when:
        or:
          - equals:
              winlog.channel: "Security"  # Explicitly drop security events
          - equals:
              log_type: "security"

# ====================== OUTPUT =======================
output.kafka:
  hosts: ["localhost:19092"]
  topic: '%{[fields.log_type]}'
  key: "winlogbeat"
  required_acks: 1
  compression: gzip
  max_retries: 2     # Further reduced
  timeout: 5s        # Reduced
  bulk_max_size: 25  # Smaller batches
  
  # Kafka metadata refresh settings
  metadata:
    refresh_frequency: 30s  # Increased for stability
    
  codec.json:
    pretty: false

# ====================== LOGGING =======================
logging.level: warning  # Changed from info to reduce logs
logging.metrics.enabled: false
logging.to_files: true
logging.files:
  path: "D:\\SIEM-BEATS\\beats-output\\internal"
  name: winlogbeat
  keepfiles: 3
  rotateeverybytes: 10485760  # 10MB - This is correct